Sync upstream changes to rsk (#29)
* Fixed message queue clearance logic in ec.message.clearAll() method

* fix: Unable to release Session : Caused by: java.io.NotSerializableException: org.apache.groovy.json.internal.LazyMap

* Add vscode to .gitignore

* Various library version updates including Freemarker, H2, Jetty, Joda, SLF4J, Log4J, and various commons and other jars; updated comments about Groovy version and some code changes for a Groovy version update but more are needed so still using same version of Groovy in this commit (most changes are for more strict rules when using @CompileStatic)

* switch to gradle 8.14.1

* address gradle 8 warnings

* more gradle 8.14 fixes

* fixed to gradle 8.14

* equal assignment to descriptions, upgrade gradle 8.14

* Allow disabled to be Y in create#UserAccount

* bump gradle to 8.14.3

* apply fixes to gradle in moqui

this resolves all warnings except java version

* bump to gradle 9.2

* ignore configuration cache for now

* switch to newest bitronix with jakarta JTA

* fix stopSearch to work with gradle 9+

* replace the rest of the exec commands

* default to opensearch and fix issues

* default to JDK 21

* upgrade first version of release notes

* already chucked out javassist from bitronix

* Update commons-lang3 and commons-beanutils versions

* allow unit tests to run under gradle 9

* add convenience tasks for testing everything

* fix failing cache facade test

* Fixed the issue that OpenSearch failed to start on macOS. (#661)

* remove redundant finalize methods, destroy exists

This helps removes warnings about non deterministic finalize which is
deprecated in newer java versions

* remove finalize, nothing to cleanup just a boolean

* remove finalize, already cleaned up correctly

close() is being called when getCompleteList(..., closeAfter) and
getPartialList(..., closeAfter). So redundant code and non deterministic
and deprecated anyway, might never be called by the JVM

* remove deprecated finalize

resource is already autoclosable by contract

* centralize dependencyUpdates and gradle 9 formatting

* upgrade all libraries, shiro now version 2

Big change, shiro bumped to version 2, one change in behavior is that
logins do not survive restarts. So I added the remember functionality in
a secure way. By default production instances will not survive login
restarts UNLESS rememberme key is generated and passed to the instance

* remove incorrect implementation of remember me

* remove shiro.ini from tests, it's no longer needed

* upgrade libraries and handle changes to API

* update changelog to incorporate all the work

* go back to INI

* fix typo now that we switched to env INI

* breakout statements to make @CompileStatic happy

* no fallback to empty string again

* return shiro.ini to tests

* fix remaining shiro2 bugs

* upgrade to groovy 5

* first round of jakarta / jetty upgrades

* switch from javax.xml.bind to jakarta

* reset to pre-groovy and expand imports

* Solve most issues in MoquiStart.java

Only one bug remains:

Failed startup of context
oeje10w.WebAppContext@2f9a01c1{ROOT,/,b=file:///home/taher/Desktop/active/repositories/fork/moqui-framework/execwartmp/ROOT/webapp/,a=STOPPED,h=oeje10s.SessionHandler@2611b9a3{STOPPED}}{file:/home/taher/Desktop/active/repositories/fork/moqui-framework/moqui.war}
java.lang.IllegalArgumentException: URI is not hierarchical

So we need to find a solution for web.xml being inside the war file

* transitional commit, still WIP for jetty / jakarta

* cleanup jetty implementation in MoquiStart, still WIP

* update and cleanup comments

* jetty logs down to warning from error

* remove another asterisk import

* go back to persisted sessions

* update comments to reflect persisted sessions

* add missing comment on license

* remove useless comments

* code self explanatory

* add comments on groovy 5

* Run Groovy shell evaluations on a dedicated executor thread

Execute Groovy shell evaluations off the WebSocket thread to avoid
blocking I/O. Introduce a volatile closing flag to coordinate async
shutdown and prevent races.

Add idle and evaluation timeouts to protect against leaked sessions and
long-running or stuck scripts. Ensure all async paths are guarded with
try/catch and consistently clean up ExecutionContext, timers, and
executor resources on close.

* absolutely no need to check against null

* restore signature of flush and close

* move from ee10 to ee11

also reintroduce servlet listener that was removed with proper updated
version

* Fix a bug introduced by Jetty confusing APIs

In MoquiStart.java, I have this very specific very clear instruction:

webappClass.getMethod("setClassLoader", ClassLoader.class).invoke(webapp, moquiStartLoader);

Yet, in MClassLoader, I added these three lines to debug:

System.out.println("=== MClassLoader constructor ===");
System.out.println("MCL = " + this);
System.out.println("MCL parent = " + parent);

AND, look at the outcome:

=== MClassLoader constructor ===
MCL = org.moqui.util.MClassLoader@77f991c
MCL parent = oejew.WebAppClassLoader{Moqui Root Webapp}@6bea52d4
Starting MClassLoader with parent org.eclipse.jetty.ee.webapp.WebAppClassLoader

Jetty is injecting its WebAppClassLoader even though there is a clear
instruction for it to disregard that class loader. Their API is
confusing at best!

This solution solved classpath problems properly by making MClassLoader
a child of StartClassLoader as intended.

* update ReleaseNotes to reflect all the updates

* upgrade all infra to latest version

Pending thorough testing. Initial tests seem to be OK

* upgrade release notes to include infra

* better organize and cleanup notes

* Fix the class loading issue from MClassLoader and preserve everything

* reintroduce char

* slightly improve MoquiStart comments

* find closest compatible call without altering structure

* less noise from jetty annotations

* limit to 2 parents for efficiency

* restore original comment with "parent chain" fix

* cleanup and simplify

* upgrade headers for jakarta

* provide better documentation for how class loading works

* update comment to match updated call

* add useful comment on why join()

* Finally solve last classpath issue

With this fix, moqui runs properly on both embedded mode AND when
deployed on a servlet container. Need to add documentation on how to
test in a servlet container.

* move outside execWar, candidates eventually to delete

* logging not used in MoquiStart

* cleanup unused dependencies

* fix a bug in jetty 12.1 EE11 on websocket sessions

Apparently in jetty 12 on EE10+ due to the separation of websockets and
EE stack from server stack, we cannot retrieve the HTTP session from
websocket handshake. Therefore fixing the bug in both UserFacade and
MoquiAbstractEndpoint accordingly.

https://github.com/jetty/jetty.project/issues/11809

* fix the same bug with respect to fetching ip address

* Revert "fix the same bug with respect to fetching ip address"

This reverts commit 2afc70c463855c02940a904f922ddb717121bda3.

* cleanup dependencies & apply futher jakarta names

* improve the comment for maximum clarity

* correct for running tests properly

* fix remaining jetty web socket based session bugs

* fully tested and solved sending emails

* add note on jakarta switch

* comment too old, no longer applicable

* update comment on heap size

* move to first stable version of bitronix

* fix the expose incorrect keyword

* fix issues with upgrading infrastructure:

- opensearch generates more files, added them to gitignore
- moqui creates two unnamed volumes because of dockerfile. The
  right solution is to add them in compose files as runtime binds
- US/Pacific is no longer an acceptable timezone for postgres so using
  standard UTC for safety on all compose files
- opensearch enforces very strictly a password with minimum requirements
  that cannot be overridden. Therefore changing it in all compose files

* Add a basic README.md in docker to explain how to use it

* add more thorough documentation to README

* a few more improvements to README in docker

* remove "expose" key, not allowed in recent docker-compose

* remove generated conf files

* bump Configuration.VERSION of freemarker to match

* fix the framework version to 4.0.0

* Allow running gradle getRuntime

* Create setupVscode gradle task

* Make postgres_backup keep have better default for what data is saved

* add note on how to override default image

* Fix ./gradlew setupVsCode

* fix: exclude old jakarta.mail and jakarta.activation dependencies from 'org.apache.commons:commons-email2-jakarta:2.0.0-M1

* remove outdated comment

* another outdated comment

* revert earlier work causing elastic search bugs

* these tasks are not needed, test runs for all components

It turns out the issue was not running all tests, but rather
one failure stops all components

* change EntityValue API to solve ambiguity bug

Groovy 4+ introduced a change in the way property to method mapping happens as
[documented](https://groovy-lang.org/style-guide.html#_getters_and_setters).

This introduced a bug that occurs when querying an entity that has a field named
`entityName`. The bug occurs because the query returns an object of type
`org.moqui.entity.EntityValue`. The problem is that the EntityValue class has a
method called getEntityName() and as per the groovy 4+ behavior this function is
called when trying to access a field named `entityName`. Sample code:

```
def someMember = ec.entity
    .find('moqui.entity.view.DbViewEntityMember')
    .condition(...)
    .one()
someMember.entityName // BUG returns .getEntityName(), not .get('entityName')
```

* fix bug in wiki services missing function call

* Fix RestClient idleTimeout ignoring timeoutSeconds > 30

* change TZ to UTC to work with docker databases

* Update addons.xml

* fix bug where image cannot receive commands (load, help)

* forgot to update the yaml files

* Update addons with pre moqui 4.0 release version tags, and fix for no versions

* Update all addons.xml components with versions for latest code

* Update versions and documentation for current release

* Update addons.xml versions and fix RestClient CompletableResponseListener

* Update addons.xml versions and fix RestClient CompletableResponseListener

* Update badge links for version 4.0.0

* Add get jdbc for postgres and mysql gradle task, add moquidemo actions release

* Update workflow to include additional components

* Add mavenCentral and remove moquidemo release

---------

Co-authored-by: Deepak Dixit <deepak.dixit@hotwax.co>
Co-authored-by: Hans Bakker <h.bakker@antwebsystems.com>
Co-authored-by: David E. Jones <dej@dejc.com>
Co-authored-by: acetousk <acetousk@users.noreply.github.com>
Co-authored-by: Taher Alkhateeb <taher@pythys.com>
Co-authored-by: Wei Zhang <zhangwei@apache.org>
Co-authored-by: Acetousk <29029373+acetousk@users.noreply.github.com>
Co-authored-by: Jens Hardings <jhp@moit.cl>
Co-authored-by: Karthik Ks <karthik.ks@azentio.com>